name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ci:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: terraform FMT
#        run: terraform -chdir=terraform fmt -check -recursive

      - name: terragrunt FMT
        run: terragrunt hclfmt --terragrunt-check --terragrunt-working-dir terragrunt
